
name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [3.1, 3.2, 3.3]
        experimental: [false]
    name: "RSpec tests: Ruby ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.version }}
      # - name: Run RuboCop
      #   run: bundle exec rubocop .
      - name: Run tests
        run: bundle exec rspec
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
